sudo: true
language: cpp
os:
- osx
compiler:
- clang
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"

script:
- brew update && brew install llvm
- mkdir -p ../CastXMLSuperbuild-build && cd ../CastXMLSuperbuild-build
- brew list llvm | grep LLVMConfig.cmake
- cmake -DUSE_SYSTEM_LLVM:BOOL=ON -DLLVM_DIR=/usr/local/Cellar/llvm/6.0.1/lib/cmake/llvm ../CastXMLSuperbuild && make -j4
- cd castxml-prefix/src/castxml-build && ctest && cd ../../..
- tar cvf castxml-macosx.tar castxml && gzip -9 castxml-macosx.tar
- curl -F file="@castxml-macosx.tar.gz" https://filebin.ca/upload.php
