version: 2
jobs:
  build:
    docker:
      - image: dockcross/manylinux-x64:latest
    working_directory: /usr/src/CastXMLSuperbuild
    resource_class: xlarge
    steps:
      - checkout:
          path: /usr/src/CastXMLSuperbuild
      - run:
          name: build
          command: |
            export PATH=/opt/python/cp36-cp36m/bin:${PATH}
            ./centos-build.sh
      - store_artifacts:
          path: /usr/src/CastXMLSuperbuild-build/castxml-linux.tar.gz
          destination: castxml-linux.tar.gz

workflows:
    version: 2
    build:
      jobs:
        - build
